# Generated by Django 6.0.2 on 2026-02-10 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('basic', 'Licencia Básica'), ('premium', 'Licencia Premium'), ('exclusive', 'Licencia Exclusiva')], default='basic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.license')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracks.track')),
            ],
        ),
    ]
