# Generated by Django 6.0.2 on 2026-03-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('basic', 'Licencia Básica'), ('premium', 'Licencia Premium'), ('exclusive', 'Licencia Exclusiva')], default='basic', max_length=20)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracks.track')),
            ],
        ),
    ]
