# Generated by Django 5.2.5 on 2026-02-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('tracks', '0002_alter_track_audio_file_alter_track_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        
        
        
    ]
