# Generated by Django 6.0.2 on 2026-02-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('tracks', '0002_alter_track_audio_file'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracks.track'),
        ),
        migrations.AddField(
            model_name='license',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
