# Generated by Django 5.2.5 on 2026-02-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_license_track_license_user_alter_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
