# Generated by Django 6.0.2 on 2026-03-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_license_created_at'),
        ('payment', '0003_license_created_at_alter_license_track_and_more'),
    ]

    operations = [
    ]
