# Generated by Django 5.2.5 on 2026-02-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_license_track_license_user_delete_purchase'),
        ('payment', '0003_alter_license_id'),
    ]

    operations = [
    ]
