# Generated by Django 6.0.2 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='tracks_files/')),
                ('bpm', models.PositiveIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tracks_covers/')),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
