# Generated by Django 5.2.5 on 2026-02-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_audio_file'),
        ('tracks', '0003_alter_track_id'),
    ]

    operations = [
    ]
