# Generated by Django 5.2.5 on 2026-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tracks_covers/'),
        ),
    ]
