# Generated by Django 5.2.5 on 2026-03-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_track_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
