# Generated by Django 6.0.2 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_track_genre_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(),
        ),
    ]
