# Generated by Django 6.0.2 on 2026-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_track_sales_count_alter_track_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='sales_count',
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.IntegerField(),
        ),
    ]
