# Generated by Django 6.0.2 on 2026-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_remove_track_sales_count_alter_track_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='stock',
        ),
        migrations.AddField(
            model_name='track',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(),
        ),
    ]
