# Generated by Django 5.2.5 on 2026-05-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_remove_track_stock_track_sales_count_alter_track_bpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='price',
        ),
    ]
